name: build-android

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
jobs:

  build-android:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cfg:
          - {target: android, arch: armv7}
          - {target: android, arch: arm64}
          - {target: android, arch: x86}
          - {target: android, arch: x86_64}
    env:
     TARGET: ${{matrix.cfg.target}}
     ARCH: ${{matrix.cfg.arch}}
    steps:
      - name: Determine Release
      id: vars
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "::set-output name=tag::nightly"
          echo "::set-output name=release::nightly"
        elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
          echo "::set-output name=tag::bleeding"
          echo "::set-output name=release::bleeding"
        fi
    - uses: actions/checkout@v2
    - name: Scripts Calc Formula - ${{matrix.cfg.target}} - ${{matrix.cfg.arch}}
      run: ./scripts/calculate_formulas.sh
    - name: Scripts Install
      run: ./scripts/$TARGET/install.sh
    - name: build
      run: ./scripts/build.sh
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
    - name: Update Release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.vars.outputs.tag }}
        release: ${{ steps.vars.outputs.release }}
        prerelease: false
        files: out/openFrameworksLibs_android_NDK24_${{matrix.cfg.arch}}.tar.bz2
      if: (github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding'))

